package com.kinect;

import javax.swing.JOptionPane;

import com.dao.SqlHelper;
import com.item.PersonItem;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author stone
 */
public class JfDelPerson extends javax.swing.JFrame {

	/**
	 * Creates new form NewJFrame3
	 */
	public JfDelPerson() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jl_id = new javax.swing.JLabel();
		jtx_id = new javax.swing.JTextField();
		jb_ok = new javax.swing.JButton();
		jb_cancle = new javax.swing.JButton();
		jl_name = new javax.swing.JLabel();
		jtx_name = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jl_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jl_id.setText("编号");
		jl_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		jb_ok.setText("确认");
		jb_ok.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jb_okActionPerformed(evt);
			}
		});

		jb_cancle.setText("取消");
		jb_cancle.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jb_cancleActionPerformed(evt);
			}
		});

		jl_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jl_name.setText("姓名");
		jl_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(61, 61, 61)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 64,
										javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 64,
								javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jb_ok))
						.addGap(51, 51, 51)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jtx_id, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jb_cancle).addComponent(jtx_name, javax.swing.GroupLayout.PREFERRED_SIZE,
										100, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(134, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(82, 82, 82)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jtx_id, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
								.addComponent(jl_id, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(33, 33, 33)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jl_name, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
								.addComponent(jtx_name, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
						.addGap(44, 44, 44)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jb_ok).addComponent(jb_cancle))
						.addGap(48, 48, 48)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jPanel1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addContainerGap()));

		pack();
	}// </editor-fold>

	private void jb_okActionPerformed(java.awt.event.ActionEvent evt) {
		PersonItem person = new PersonItem();
		String personId = jtx_id.getText();
		String name = jtx_name.getText();
		if (person.equals("") && person.equals("")) {
			person.setName(name);
			person.setPersonId(personId);
			SqlHelper sqlHelper = new SqlHelper();
			boolean success = sqlHelper.addPerson(person);
			if(success){
	        	JOptionPane.showMessageDialog(this, "删除成功!","提示",JOptionPane.WARNING_MESSAGE);
	        }else {
	        	JOptionPane.showMessageDialog(this, "删除失败!","提示",JOptionPane.WARNING_MESSAGE);
			}
		}else {
			JOptionPane.showMessageDialog(this, "请输入编号和姓名!","提示",JOptionPane.WARNING_MESSAGE);
		}
	}

	private void jb_cancleActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	// public static void main(String args[]) {
	// /* Set the Nimbus look and feel */
	// //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
	// (optional) ">
	// /* If Nimbus (introduced in Java SE 6) is not available, stay with the
	// default look and feel.
	// * For details see
	// http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	// */
	// try {
	// for (javax.swing.UIManager.LookAndFeelInfo info :
	// javax.swing.UIManager.getInstalledLookAndFeels()) {
	// if ("Nimbus".equals(info.getName())) {
	// javax.swing.UIManager.setLookAndFeel(info.getClassName());
	// break;
	// }
	// }
	// } catch (ClassNotFoundException ex) {
	// java.util.logging.Logger.getLogger(JfDelPerson.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// } catch (InstantiationException ex) {
	// java.util.logging.Logger.getLogger(JfDelPerson.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// } catch (IllegalAccessException ex) {
	// java.util.logging.Logger.getLogger(JfDelPerson.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	// java.util.logging.Logger.getLogger(JfDelPerson.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// }
	// //</editor-fold>
	//
	// /* Create and display the form */
	// java.awt.EventQueue.invokeLater(new Runnable() {
	// public void run() {
	// new JfDelPerson().setVisible(true);
	// }
	// });
	// }

	// Variables declaration - do not modify
	private javax.swing.JPanel jPanel1;
	private javax.swing.JButton jb_cancle;
	private javax.swing.JButton jb_ok;
	private javax.swing.JLabel jl_id;
	private javax.swing.JLabel jl_name;
	private javax.swing.JTextField jtx_id;
	private javax.swing.JTextField jtx_name;
	// End of variables declaration
}
